### ISSUE TITLE
PsychoPy for software tools?

### ISSUE THREAD

**Issue by peircej** [jasiek-net/awesome-psychology-projects#1]
It's embarrassing to self-promote but a lot of PsychoPy users (and there are [over 30,000 of them](https://usage.psychopy.org/)) report that they're (ahem) quite keen on PsychoPy. The project has been open source since 2002 originally purely volunteer-based but now with professional support from services (like experiment hosting and consultancy work)

See the [PsychoPy homepage](https://psychopy.org) or the [PsychoPy GitHub repo](https://github.com/psychopy/psychopy) for more info

**Comment by jasiek-net** [comment]
Great, thanks for reaching out, I added project to list :)
